#! /bin/sh

sxhkd &
setxkbmap us
~/.fehbg &
~/.config/polybar/launch.sh &
udiskie &
compton &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         1
bspc config window_gap           0

bspc config focused_border_color "#D0D0D0"
bspc config active_border_color  "#333333"
bspc config urgent_border_color  "#B82C2D"

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle true

bspc rule -a "Firefox" desktop = '^2' follow = on
bspc rule -a "Steam" desktop = '^3' follow = on
bspc rule -a "PPSSPP" desktop = '^3' follow = on
bspc rule -a "DOSBox" desktop = '^3' follow = on
bspc rule -a "GNU Image Manipulation Program" desktop = '^4' follow = on
bspc rule -a "mpv" desktop = '^5' follow = on
bspc rule -a "TeamSpeak 3" desktop = '^7' follow = on
bspc rule -a "Discord" desktop = '^7' follow = on
